Repository zephir-lang/zephir, pull requests merged in 2021-04, with the labels that each got.

#2181 #2180 - Default `null` on type `string`
  CHANGELOG.md
  Library/Backends/ZendEngine2/Backend.php
  Library/Backends/ZendEngine3/Backend.php
  Library/Backends/ZendEngine3/VariablesManager.php
  Library/BaseBackend.php
  Library/Expression/Reference.php
  composer.lock
  ext/config.m4
  ext/config.w32
  ext/stub.c
  ext/stub.h
  ext/stub/concat.zep.c
  ext/stub/flow.zep.c
  ext/stub/interfaces/interfacestaticmethod.zep.c
  ext/stub/interfaces/interfacestaticmethod.zep.h
  ext/stub/invokes/abstractprotected.zep.c
  ext/stub/mcall.zep.c
  ext/stub/oo/extendpdoclass.zep.c
  ext/stub/reflection.zep.c
  ext/stub/reflection.zep.h
  ext/stub/router/route.zep.c
  ext/stub/strings.zep.c
  ext/stub/vars.zep.c
  tests/Extension/MCallTest.php
Labels: bug

#2185 Class method params review
  Library/ClassMethod.php
  Library/ClassMethodParameters.php
Labels: enhancement

#2188 #642 - Add test case
  stub/closures.zep
  tests/Extension/ClosureTest.php
Labels: enhancement

#2190 #1187 - Add test case
  stub/arraymanipulation.zep
  tests/Extension/ArrayManipulationTest.php
Labels: enhancement

#2191 #663 - Add test case
  stub/issue663.zep
  tests/Extension/Issue663Test.php
Labels: enhancement

#2194 #828 - Fix cast `string` to `int` and `float`
  CHANGELOG.md
  kernels/ZendEngine3/operators.c
  stub/cast.zep
  tests/Extension/CastTest.php
Labels: bug

#2195 #1212 - Add test case
  stub/spl.zep
  tests/Extension/SplTest.php
Labels: enhancement

#2192 #812 - Fix `uint` cast to abs in function params
  CHANGELOG.md
  Library/Backends/ZendEngine2/Backend.php
  Library/ClassMethod.php
  kernels/ZendEngine3/object.c
  stub/arithmetic.zep
  tests/Extension/ArithmeticTest.php
Labels: bug

#2197 #2186 - Fix `null` strict check
  CHANGELOG.md
  Library/Operators/Arithmetical/AddOperator.php
  Library/Operators/Arithmetical/ArithmeticalBaseOperator.php
  Library/Operators/Arithmetical/DivOperator.php
  Library/Operators/Arithmetical/ModOperator.php
  Library/Operators/Arithmetical/MulOperator.php
  Library/Operators/Arithmetical/SubOperator.php
  Library/Operators/BaseOperator.php
  Library/Operators/Bitwise/BitwiseAndOperator.php
  Library/Operators/Bitwise/BitwiseBaseOperator.php
  Library/Operators/Bitwise/BitwiseOrOperator.php
  Library/Operators/Bitwise/BitwiseXorOperator.php
  Library/Operators/Bitwise/ShiftLeftOperator.php
  Library/Operators/Bitwise/ShiftRightOperator.php
  Library/Operators/Comparison/ComparisonBaseOperator.php
  Library/Operators/Comparison/EqualsOperator.php
  Library/Operators/Comparison/GreaterEqualOperator.php
  Library/Operators/Comparison/GreaterOperator.php
  Library/Operators/Comparison/IdenticalOperator.php
  Library/Operators/Comparison/LessEqualOperator.php
  Library/Operators/Comparison/LessOperator.php
  Library/Operators/Comparison/NotEqualsOperator.php
  Library/Operators/Comparison/NotIdenticalOperator.php
  Library/Operators/Logical/AndOperator.php
  Library/Operators/Logical/OrOperator.php
  Library/Operators/Other/NewInstanceOperator.php
  Library/Operators/Other/NewInstanceTypeOperator.php
  Library/Operators/Other/TypeHintOperator.php
  Library/Operators/Other/UnlikelyOperator.php
  kernels/ZendEngine3/operators.h
  stub/strings.zep
  tests/Extension/StringTest.php
Labels: bug

#2198 #938 - Add test case
  tests/Extension/Oo/OoParamsTest.php
Labels: enhancement, testing

#2199 #645 - Add test case
  stub/arrayaccessobj.zep
  stub/arrayaccesstest.zep
  tests/Extension/ArrayAccessTest.php
Labels: enhancement, testing

#2200 #1036 - Add test case
  stub/closures.zep
  tests/Extension/ClosureTest.php
Labels: enhancement, testing

#2201 #1155 - Add test case
  stub/arrayaccesstest.zep
  tests/Extension/ArrayAccessTest.php
Labels: enhancement, testing

#2202 #1136 - Add test case
  stub/mcall.zep
  tests/Extension/MCallTest.php
Labels: enhancement, testing

#2204 #2186 - Change empty string check from `IS_UNDEF` to `ZEPHIR_IS_EMPTY`
  Library/Backends/ZendEngine3/Backend.php
  Library/Optimizers/EvalExpression.php
  stub/strings.zep
  tests/Extension/StringTest.php
Labels: bug

#2205 Improve generated C code
  Library/Backends/ZendEngine2/Backend.php
  Library/Backends/ZendEngine3/Backend.php
  Library/ClassDefinition.php
  Library/ClassMethod.php
  Library/ClassProperty.php
  Library/CodePrinter.php
  Library/Operators/Other/NewInstanceOperator.php
Labels: enhancement

#2210 #597 - Add test case
  ext/stub/assign.zep.c
  ext/stub/assign.zep.h
  stub/assign.zep
  tests/Extension/AssignTest.php
Labels: enhancement, testing

#2212 #914 - mysqli constructor
  .github/workflows/build-windows.yml
  Library/StaticCall.php
  docker-compose.yml
  docker/7.4/Dockerfile
  docker/8.0/Dockerfile
  stub/issue914.zep
  tests/Extension/Issue914Test.php
Labels: enhancement, testing

#2211 #1094 - Fix nullable array
  CHANGELOG.md
  Library/Backends/ZendEngine3/Backend.php
  Library/ClassMethod.php
  Library/Operators/Comparison/ComparisonBaseOperator.php
  ext/stub/arrayaccesstest.zep.c
  ext/stub/arrayaccesstest.zep.h
  ext/stub/flow/switchflow.zep.c
  ext/stub/globals/serverrequestfactory.zep.c
  ext/stub/mcall.zep.c
  stub/arrayaccesstest.zep
  tests/Extension/ArrayAccessTest.php
  tests/Extension/MCallTest.php
Labels: bug

#2216 #774 - Add test case
  ext/config.m4
  ext/config.w32
  ext/stub.c
  ext/stub.h
  ext/stub/arraymanipulation.zep.c
  ext/stub/arraymanipulation.zep.h
  stub/arraymanipulation.zep
  tests/Extension/ArrayManipulationTest.php
Labels: testing

#2217 #1086 - Add test case
  ext/stub/arrayaccesstest.zep.c
  ext/stub/arrayaccesstest.zep.h
  stub/arrayaccesstest.zep
  tests/Extension/ArrayAccessTest.php
Labels: testing

#2218 Review composer dependencies
  Library/Compiler.php
  Library/CompilerFile.php
  Library/Console/Command/CleanCommand.php
  Library/Console/Command/FullCleanCommand.php
  Library/DependencyInjection/ZephirKernel.php
  Library/FileSystem/HardDisk.php
  Library/Logger/Formatter/CompilerFormatter.php
  Library/StaticCall.php
  Library/config/config.yml
  Library/config/services.yml
  composer.json
  composer.lock
  tests/services.yml
Labels: enhancement

#2219 #887 - Add test case
  ext/config.m4
  ext/config.w32
  ext/stub.c
  ext/stub.h
  ext/stub/issue887.zep.c
  ext/stub/issue887.zep.h
  stub/issue887.zep
  tests/Extension/Issue887Test.php
Labels: testing

#2220 #1803 - Add test case
  ext/config.m4
  ext/config.w32
  ext/stub.c
  ext/stub.h
  ext/stub/constructors/issue1803.zep.c
  ext/stub/constructors/issue1803.zep.h
  stub/constructors/issue1803.zep
  tests/Extension/Constructors/Issue1803Test.php
Labels: testing

#2223 #1245 - Add test case for `get_object_vars()`
  ext/config.m4
  ext/config.w32
  ext/stub.c
  ext/stub.h
  ext/stub/properties/getobjectvars.zep.c
  ext/stub/properties/getobjectvars.zep.h
  ext/stub/properties/staticprotectedproperties.zep.c
  stub/properties/getobjectvars.zep
  tests/Extension/Properties/GetObjectVarsTest.php
Labels: testing

#2225 #1134 - Fix default value detection with `Reflection`
  CHANGELOG.md
  Library/ArgInfoDefinition.php
  ext/config.m4
  ext/config.w32
  ext/stub.c
  ext/stub.h
  ext/stub/arrayaccesstest.zep.h
  ext/stub/globals/serverrequestfactory.zep.h
  ext/stub/issue1134.zep.c
  ext/stub/issue1134.zep.h
  ext/stub/issue2165/issue.zep.h
  ext/stub/mcall.zep.h
  ext/stub/oo/ooparams.zep.h
  ext/stub/typehinting/testabstract.zep.h
  ext/stub/vars.zep.h
  stub/issue1134.zep
  tests/Extension/Issue1134Test.php
Labels: bug

#2215 #1103 - Added support syntax assign-bitwise operators
  CHANGELOG.md
  Library/Expression/Builder/Operators/AssignVariableOperator.php
  Library/Statements/LetStatement.php
  stub/assign.zep
  tests/Extension/AssignTest.php
Labels: enhancement, nfr

#2227 #2226 - Update list of class entries for PHP extension 'date'
  CHANGELOG.md
  Library/ClassDefinition.php
Labels: bug

#2214 #203 - Add support syntax `passing variables by reference`
  CHANGELOG.md
  Library/ArgInfoDefinition.php
  Library/ClassMethod.php
  Library/ClassMethodParameters.php
  Library/Expression/ClosureArrow.php
  stub/functions.zep
  tests/Extension/FunctionsTest.php
Labels: nfr

#2222 #1259 - Fix unset from class property
  CHANGELOG.md
  Library/Backends/ZendEngine2/Backend.php
  Library/Backends/ZendEngine3/StringsManager.php
  Library/Statements/Let/StaticProperty.php
  Library/Statements/UnsetStatement.php
  ext/kernel/array.c
  ext/kernel/concat.c
  ext/kernel/object.c
  ext/kernel/operators.c
  ext/stub/arrayaccessobj.zep.c
  ext/stub/arrayaccesstest.zep.c
  ext/stub/arrayaccesstest.zep.h
  ext/stub/assign.zep.c
  ext/stub/assign.zep.h
  ext/stub/concat.zep.c
  ext/stub/unsettest.zep.c
  kernels/ZendEngine3/array.c
  kernels/ZendEngine3/object.c
  kernels/ZendEngine3/operators.c
  stub/arrayaccesstest.zep
  tests/Extension/ArrayAccessTest.php
Labels: bug

#2230 #1259 - Fix unset property via variable
  Library/Statements/UnsetStatement.php
  ext/stub/arrayaccessobj.zep.c
  ext/stub/arrayaccesstest.zep.c
  ext/stub/arrayaccesstest.zep.h
  ext/stub/unsettest.zep.c
  stub/arrayaccesstest.zep
  tests/Extension/ArrayAccessTest.php
Labels: bug

#2233 #2232 - Fix cast string from null
  CHANGELOG.md
  Library/Operators/Other/CastOperator.php
  kernels/ZendEngine3/operators.h
  stub/cast.zep
  tests/Extension/CastTest.php
Labels: bug

#2235 #2234 - Fix strict nullable string type on null value
  CHANGELOG.md
  Library/Backends/ZendEngine2/Backend.php
  stub/strings.zep
  tests/Extension/StringTest.php
Labels: bug

#2236 0.13.4
  CHANGELOG.md
  Library/Backends/ZendEngine2/Backend.php
  Library/Operators/Other/CastOperator.php
  Library/Zephir.php
  ext/kernel/operators.h
  ext/php_stub.h
  ext/stub/arrayaccesstest.zep.c
  ext/stub/cast.zep.c
  ext/stub/cast.zep.h
  ext/stub/compare.zep.c
  ext/stub/exception.zep.c
  ext/stub/mcall.zep.c
  ext/stub/oo/dynamicprop.zep.c
  ext/stub/oo/oodestruct.zep.c
  ext/stub/oo/ooparams.zep.c
  ext/stub/properties/propertyarray.zep.c
  ext/stub/requires.zep.c
  ext/stub/router/route.zep.c
  ext/stub/strings.zep.c
  ext/stub/strings.zep.h
  ext/stub/typeinstances.zep.c
  ext/stub/vars.zep.c
  kernels/ZendEngine3/operators.h
  stub/cast.zep
  stub/strings.zep
  tests/Extension/CastTest.php
  tests/Extension/StringTest.php
Labels: release
