Repository zephir-lang/zephir, pull requests merged in 2021-10, with the labels that each got.

#2296 Remove `league/flysystem` package
  Library/FileSystem/FileSystemInterface.php
  Library/FileSystem/HardDisk.php
  composer.json
  composer.lock
Labels: enhancement

#2297 #2283 - Fix multi return types stubs
  CHANGELOG.md
  Library/Backends/ZendEngine3/StringsManager.php
  Library/CacheManager.php
  Library/ClassConstant.php
  Library/CompiledExpression.php
  Library/CompilerFile.php
  Library/CompilerFileAnonymous.php
  Library/DependencyMap.php
  Library/FileSystem/HardDisk.php
  Library/Operators/Logical/LogicalBaseOperator.php
  Library/Passes/CallGathererPass.php
  Library/StaticCall.php
  Library/StringsManager.php
  Library/Stubs/Generator.php
  Library/TypeAwareInterface.php
  Library/Types.php
  Library/Variable.php
  stub/stubs.zep
Labels: bug, enhancement, hacktoberfest-accepted

#2298 #2273 - Remove `.zep` from stubs filenames
  CHANGELOG.md
  Library/ArgInfoDefinition.php
  Library/Stubs/Generator.php
  tests/Zephir/Stubs/GeneratorTest.php
  tests/fixtures/stubs/issues/expected/Exception.php
  tests/fixtures/stubs/issues/expected/Issue_1778.php
  tests/fixtures/stubs/issues/expected/Issue_1900.php
  tests/fixtures/stubs/issues/expected/Issue_1900_PHP70.zep.php
  tests/fixtures/stubs/issues/expected/Issue_1907.php
  tests/fixtures/stubs/issues/expected/Issue_1922.php
  tests/fixtures/stubs/issues/expected/Issue_1986.php
  tests/fixtures/stubs/issues/expected/Issue_1986.zep.php
  tests/fixtures/stubs/issues/expected/Issue_2026.php
  tests/fixtures/stubs/issues/expected/Issue_2092.php
  tests/fixtures/stubs/issues/expected/Issue_2092_PHP70.zep.php
  tests/sharness/t0005-stubs.sh
Labels: enhancement, hacktoberfest-accepted

#2300 #2272 - Fix bool return type in stubs
  Library/Stubs/MethodDocBlock.php
  stub/stubs.zep
Labels: bug, enhancement, ide, hacktoberfest-accepted

#2301 Static analysis
  .github/workflows/main.yml
Labels: Hacktoberfest, hacktoberfest-accepted

#2302 Mass code refactor
  .github/workflows/main.yml
  CHANGELOG.md
  Library/Branch.php
  Library/ClassDefinition.php
  Library/CompilerFile.php
  Library/Documentation/DocblockParser.php
  Library/Documentation/File/ClassFile.php
  Library/Documentation/NamespaceAccessor.php
  Library/Expression.php
  Library/Operators/Other/ConcatOperator.php
  Library/Optimizers/EvalExpression.php
  Library/Optimizers/IsTypeOptimizerAbstract.php
  Library/Optimizers/MathOptimizer.php
  Library/Optimizers/OptimizerAbstract.php
  Library/StatementsBlock.php
  prototypes/apc.php
Labels: enhancement, Hacktoberfest

#2303 #2280 - Add `string` support in php.ini
  CHANGELOG.md
  Library/Backends/ZendEngine2/Backend.php
  Library/Backends/ZendEngine3/Backend.php
  Library/Compiler.php
  Library/Optimizers/FunctionCall/GlobalsGetOptimizer.php
  Library/Optimizers/FunctionCall/GlobalsSetOptimizer.php
  config.json
  ext/php_stub.h
  ext/stub.c
  ext/stub/globals.zep.c
  ext/stub/globals.zep.h
  stub/globals.zep
  tests/Extension/GlobalsTest.php
Labels: nfr, Hacktoberfest, hacktoberfest-accepted

#2288 #2276 - Add support for `mixed` type
  CHANGELOG.md
  Library/ArgInfoDefinition.php
  Library/Backends/ZendEngine3/Backend.php
  Library/ClassMethod.php
  Library/ClassMethodParameters.php
  Library/Exception/InvalidTypeException.php
  Library/Expression.php
  Library/Expression/Closure.php
  Library/Expression/ClosureArrow.php
  Library/Expression/NativeArray.php
  Library/Statements/ReturnStatement.php
  Library/SymbolTable.php
  ext/config.m4
  ext/config.w32
  ext/stub.c
  ext/stub.h
  ext/stub/types/mixedtype.zep.c
  ext/stub/types/mixedtype.zep.h
  stub/types/mixedtype.zep
  tests/Extension/Types/MixedTypeTest.php
Labels: nfr, Hacktoberfest, hacktoberfest-accepted

#2304 Fix unreachable warning on generate
  Library/Branch.php
  Library/Optimizers/EvalExpression.php
  Library/StatementsBlock.php
  tests/Extension/Types/MixedTypeTest.php
Labels: bug, Hacktoberfest, hacktoberfest-accepted

#2307 Add release notes parser, store Phar after build [ci skip]
  .github/workflows/release.yml
  release-notes.md
Labels: Hacktoberfest, hacktoberfest-accepted
